SET local check_function_bodies = off;

CREATE EXTENSION "vector" SCHEMA "extensions";

CREATE SEQUENCE "public"."knowledge_chunks_id_seq" AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 NO CYCLE;

CREATE SEQUENCE "public"."resource_views_id_seq" AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 NO CYCLE;

CREATE TABLE "public"."audit_logs" (
  "id"              bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "user_id"         uuid,
  "user_email"      text                     NOT NULL,
  "user_name"       text,
  "action_type"     text                     NOT NULL,
  "target_resource" text                     NOT NULL,
  "details"         jsonb                    DEFAULT '{}'::jsonb,
  "created_at"      timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "audit_logs_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."audit_logs"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."cms_folders" (
  "id"         bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "name"       text                     NOT NULL,
  "type"       text                     NOT NULL,
  "parent_id"  bigint,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "cms_folders_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."cms_folders"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."cms_settings" (
  "key_name"      text                     NOT NULL,
  "setting_value" jsonb                    NOT NULL,
  "updated_at"    timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "cms_settings_pkey" PRIMARY KEY (key_name)
);

ALTER TABLE "public"."cms_settings"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."contacts" (
  "id"         uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "name"       text                     NOT NULL,
  "email"      text                     NOT NULL,
  "company"    text,
  "message"    text                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "contacts_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."contacts"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."daily_tasks" (
  "id"            bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "title"         text                     NOT NULL,
  "reward_points" integer                  NOT NULL DEFAULT 10,
  "target_type"   text                     NOT NULL,
  "target_id"     integer,
  "is_active"     boolean                  NOT NULL DEFAULT true,
  "created_by"    text                     NOT NULL,
  "created_at"    timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "daily_tasks_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."daily_tasks"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."item_reviews" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "item_type"  text                     NOT NULL,
  "item_id"    bigint                   NOT NULL,
  "user_email" text                     NOT NULL,
  "content"    text                     NOT NULL,
  "rating"     integer                  DEFAULT 5,
  "status"     text                     DEFAULT 'pending'::text,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "item_reviews_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."item_reviews"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."knowledge_chunks" (
  "id"           bigint                   NOT NULL DEFAULT nextval('public.knowledge_chunks_id_seq'::regclass),
  "source_type"  text                     NOT NULL,
  "source_id"    integer,
  "source_title" text                     NOT NULL,
  "chunk_index"  integer                  NOT NULL DEFAULT 0,
  "content"      text                     NOT NULL,
  "embedding"    extensions.vector(768),
  "metadata"     jsonb                    DEFAULT '{}'::jsonb,
  "created_at"   timestamp with time zone DEFAULT now(),
  CONSTRAINT "knowledge_chunks_pkey" PRIMARY KEY (id),
  CONSTRAINT "knowledge_chunks_source_type_check" CHECK ((source_type = ANY (ARRAY['RESOURCE'::text, 'VIDEO'::text, 'PREMIUM'::text, 'MANUAL'::text])))
);

ALTER TABLE "public"."knowledge_chunks"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."leads" (
  "id"                bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "email"             character varying        NOT NULL,
  "full_name"         character varying,
  "phone_number"      character varying,
  "source"            character varying        NOT NULL,
  "target_item_title" character varying,
  "metadata"          jsonb                    DEFAULT '{}'::jsonb,
  "created_at"        timestamp with time zone DEFAULT now(),
  CONSTRAINT "leads_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."leads"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."orders" (
  "id"          bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "user_id"     uuid                     NOT NULL,
  "user_email"  text                     NOT NULL,
  "amount"      numeric                  NOT NULL,
  "memo_code"   text                     NOT NULL,
  "status"      text                     NOT NULL DEFAULT 'PENDING'::text,
  "created_at"  timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "updated_at"  timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "referred_by" text,
  CONSTRAINT "orders_memo_code_key" UNIQUE (memo_code),
  CONSTRAINT "orders_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."orders"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."premium_contents" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title"       text                     NOT NULL,
  "description" text,
  "category"    text                     DEFAULT 'Workflow'::text,
  "link"        text                     NOT NULL,
  "created_at"  timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "premium_contents_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."premium_contents"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."resource_views" (
  "id"          bigint                   NOT NULL DEFAULT nextval('public.resource_views_id_seq'::regclass),
  "resource_id" bigint                   NOT NULL,
  "viewed_at"   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "resource_views_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."resource_views"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."resources" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title"       text                     NOT NULL,
  "description" text,
  "type"        text,
  "link"        text                     NOT NULL,
  "ispremium"   boolean                  DEFAULT false,
  "created_at"  timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "is_premium"  boolean                  DEFAULT false,
  "folder_id"   bigint,
  CONSTRAINT "resources_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."resources"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."site_content" (
  "id"         text                     NOT NULL,
  "content"    jsonb                    NOT NULL DEFAULT '{}'::jsonb,
  "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "site_content_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."site_content"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."student_points_balance" (
  "user_email"        text                     NOT NULL,
  "points"            integer                  NOT NULL DEFAULT 0,
  "redeemed_courses"  text[]                   DEFAULT '{}'::text[],
  "last_updated"      timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "streak_count"      integer                  NOT NULL DEFAULT 0,
  "last_checkin_date" date,
  CONSTRAINT "student_points_balance_pkey" PRIMARY KEY (user_email)
);

ALTER TABLE "public"."student_points_balance"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."task_completions" (
  "id"             bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "user_email"     text                     NOT NULL,
  "task_id"        bigint,
  "completed_date" text                     NOT NULL,
  "created_at"     timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "task_completions_pkey" PRIMARY KEY (id),
  CONSTRAINT "task_completions_user_email_task_id_completed_date_key" UNIQUE (user_email, task_id, completed_date)
);

ALTER TABLE "public"."task_completions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_activity_metrics" (
  "id"            bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "user_email"    text                     NOT NULL,
  "activity_type" text                     NOT NULL,
  "target_item"   text                     NOT NULL,
  "metadata"      jsonb                    DEFAULT '{}'::jsonb,
  "created_at"    timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "user_activity_metrics_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."user_activity_metrics"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_document_progress" (
  "id"                 bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "user_email"         character varying        NOT NULL,
  "document_id"        integer                  NOT NULL,
  "seconds_read"       integer                  NOT NULL DEFAULT 0,
  "max_scroll_percent" integer                  NOT NULL DEFAULT 0,
  "is_completed"       boolean                  NOT NULL DEFAULT false,
  "completed_at"       timestamp with time zone,
  "last_updated"       timestamp with time zone DEFAULT now(),
  CONSTRAINT "unique_user_doc" UNIQUE (user_email, document_id),
  CONSTRAINT "user_document_progress_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."user_document_progress"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_video_progress" (
  "id"              bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "user_email"      character varying        NOT NULL,
  "video_id"        character varying        NOT NULL,
  "watched_seconds" integer                  NOT NULL DEFAULT 0,
  "duration"        integer                  NOT NULL DEFAULT 0,
  "is_completed"    boolean                  NOT NULL DEFAULT false,
  "completed_at"    timestamp with time zone,
  "last_updated"    timestamp with time zone DEFAULT now(),
  CONSTRAINT "unique_user_video" UNIQUE (user_email, video_id),
  CONSTRAINT "user_video_progress_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."user_video_progress"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."videos" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title"       text                     NOT NULL,
  "description" text,
  "youtubeurl"  text                     NOT NULL,
  "duration"    text,
  "isfeatured"  boolean                  DEFAULT false,
  "created_at"  timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "youtube_url" text,
  "is_featured" boolean                  DEFAULT false,
  "folder_id"   bigint,
  CONSTRAINT "videos_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."videos"
  ENABLE ROW LEVEL SECURITY;

ALTER SEQUENCE "public"."knowledge_chunks_id_seq" OWNED BY "public"."knowledge_chunks"."id";

ALTER SEQUENCE "public"."resource_views_id_seq" OWNED BY "public"."resource_views"."id";

CREATE OR REPLACE FUNCTION public.match_knowledge_chunks (
  query_embedding extensions.vector,
  match_threshold double precision  DEFAULT 0.72,
  match_count     integer           DEFAULT 5
)
  RETURNS TABLE (
    id           bigint,
    source_type  text,
    source_id    integer,
    source_title text,
    chunk_index  integer,
    content      text,
    metadata     jsonb,
    similarity   double precision
  )
  LANGUAGE sql
  STABLE
  AS $function$
  SELECT
    id, source_type, source_id, source_title, chunk_index, content, metadata,
    1 - (embedding <=> query_embedding) AS similarity
  FROM knowledge_chunks
  WHERE 1 - (embedding <=> query_embedding) > match_threshold
  ORDER BY embedding <=> query_embedding
  LIMIT match_count;
$function$;

ALTER TABLE "public"."audit_logs"
  ADD CONSTRAINT "audit_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;

ALTER TABLE "public"."cms_folders"
  ADD CONSTRAINT "cms_folders_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES public.cms_folders(id) ON DELETE CASCADE;

ALTER TABLE "public"."resources"
  ADD CONSTRAINT "resources_folder_id_fkey" FOREIGN KEY (folder_id) REFERENCES public.cms_folders(id) ON DELETE SET NULL;

ALTER TABLE "public"."resource_views"
  ADD CONSTRAINT "resource_views_resource_id_fkey" FOREIGN KEY (resource_id) REFERENCES public.resources(id) ON DELETE CASCADE;

ALTER TABLE "public"."task_completions"
  ADD CONSTRAINT "task_completions_task_id_fkey" FOREIGN KEY (task_id) REFERENCES public.daily_tasks(id) ON DELETE CASCADE;

ALTER TABLE "public"."videos"
  ADD CONSTRAINT "videos_folder_id_fkey" FOREIGN KEY (folder_id) REFERENCES public.cms_folders(id) ON DELETE SET NULL;

CREATE INDEX idx_doc_progress_user ON public.user_document_progress USING btree (user_email);

CREATE INDEX idx_knowledge_chunks_source ON public.knowledge_chunks USING btree (source_type, source_id);

CREATE INDEX idx_leads_email ON public.leads USING btree (email);

CREATE INDEX idx_leads_phone ON public.leads USING btree (phone_number);

CREATE INDEX idx_resource_views_resource_id ON public.resource_views USING btree (resource_id);

CREATE INDEX idx_resource_views_viewed_at ON public.resource_views USING btree (viewed_at);

CREATE INDEX idx_student_points_email ON public.student_points_balance USING btree (user_email);

CREATE INDEX idx_video_progress_user ON public.user_video_progress USING btree (user_email);

CREATE POLICY "Allow admins to view audit logs" ON "public"."audit_logs"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Allow service role to insert audit logs" ON "public"."audit_logs"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (true);

CREATE POLICY "Allow all folder navigation" ON "public"."cms_folders"
  FOR ALL
  TO PUBLIC
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Cho phép khach gui form" ON "public"."contacts"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (true);

CREATE POLICY "Allow full task management" ON "public"."daily_tasks"
  FOR ALL
  TO PUBLIC
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to insert" ON "public"."item_reviews"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.role() = 'authenticated'::text));

CREATE POLICY "Allow public read approved reviews" ON "public"."item_reviews"
  FOR SELECT
  TO PUBLIC
  USING ((status = 'approved'::text));

CREATE POLICY "Public read knowledge" ON "public"."knowledge_chunks"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Service role full access" ON "public"."knowledge_chunks"
  FOR ALL
  TO PUBLIC
  USING ((auth.role() = 'service_role'::text));

CREATE POLICY "Allow insert orders anonymous" ON "public"."orders"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (true);

CREATE POLICY "Allow select orders access" ON "public"."orders"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Allow update orders webhook" ON "public"."orders"
  FOR UPDATE
  TO PUBLIC
  USING (true);

CREATE POLICY "Allow public read access" ON "public"."premium_contents"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Allow public insert" ON "public"."resource_views"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (true);

CREATE POLICY "Allow public select" ON "public"."resource_views"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Allow public delete on resources" ON "public"."resources"
  FOR DELETE
  TO PUBLIC
  USING (true);

CREATE POLICY "Allow public insert on resources" ON "public"."resources"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (true);

CREATE POLICY "Allow public select on resources" ON "public"."resources"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Allow public update on resources" ON "public"."resources"
  FOR UPDATE
  TO PUBLIC
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow public read access" ON "public"."site_content"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Allow internal point processing" ON "public"."student_points_balance"
  FOR ALL
  TO PUBLIC
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow track execution logs" ON "public"."task_completions"
  FOR ALL
  TO PUBLIC
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow admins to read telemetry" ON "public"."user_activity_metrics"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Allow internal telemetry insertion" ON "public"."user_activity_metrics"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (true);

CREATE POLICY "Allow public delete on videos" ON "public"."videos"
  FOR DELETE
  TO PUBLIC
  USING (true);

CREATE POLICY "Allow public insert on videos" ON "public"."videos"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (true);

CREATE POLICY "Allow public select on videos" ON "public"."videos"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Allow public update on videos" ON "public"."videos"
  FOR UPDATE
  TO PUBLIC
  USING (true)
  WITH CHECK (true);

COMMENT ON EXTENSION "vector" IS 'vector data type and ivfflat and hnsw access methods';

GRANT EXECUTE ON FUNCTION "public"."match_knowledge_chunks"(extensions.vector, double precision, integer) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."knowledge_chunks_id_seq" TO "anon", "authenticated", "postgres", "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."resource_views_id_seq" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."audit_logs" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."cms_folders" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."cms_settings" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."contacts" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."daily_tasks" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."item_reviews" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."knowledge_chunks" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."leads" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."orders" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."premium_contents" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."resource_views" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."resources" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."site_content" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."student_points_balance" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."task_completions" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_activity_metrics" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_document_progress" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_video_progress" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."videos" TO "anon", "authenticated", "postgres", "service_role";

